cx_offset: 0.0
cy_offset: 0.0
crop_size: 1800
translation: [0.02, -0.004, -0.245]
rotation_deg: [-0.0, 1.8, 1.6]
# translation: [0, 0, 0]
# rotation_deg: [0, 0, 0]
gpu: true
out_width: 3600
out_height: 1800